### ISSUE TITLE
Night jumping pawn

### ISSUE THREAD

**Issue by MichaelChar** [Radu-Sebastian/Python-Chess-AI#1]
Hi love your code, you are a genius to have thought of this so congrats.

i have only 1 small problem, if i click on play vs AI(white)/play vs AI(black)/play vs strong AI(white) and the use either the queens night(play vs AI(white)/play vs strong AI(white)) or the kings night(play vs AI(black) to jump over either the c3(play vs AI(white)/play vs strong AI(white)) or f6(play vs AI(black)) pawn, not only will they disapear, but the respective player will get another turn. i tried fixing it myself, but my code is nowhere near as good so i could not.

love your work, thanks in advance!

**Comment by Radu-Sebastian** [comment]
Hello and thank you very much for your kind words! I still have a lot of work to do: this issue has been for a while and I am still searching to find out the reason of the bug, expect some updates in the near future

**Comment by MichaelChar** [comment]
Maybe instead of fixing the bug, you could put on a condition that if a pawn is present on one move, and on the next move it disapears while a night is moved(so not captured), "respawn" the pawn and set the move to the opponent.

**Comment by MichaelChar** [comment]
also i dont think your bot registers double attacks(with a queen attacking the king and rook at the same time, so the rook will end up eaten)

**Comment by Radu-Sebastian** [comment]
https://github.com/Radu-Sebastian/Python-Chess-AI-With-Digital-Board-Recognition-And-MCTS
