### ISSUE TITLE
Double attack

### ISSUE THREAD

**Issue by MichaelChar** [Radu-Sebastian/Python-Chess-AI#2]
I dont think your bot registers double attacks(with a queen attacking the king and rook at the same time, so the rook will end up eaten)

**Comment by Radu-Sebastian** [comment]
Hi,  I am currently improving this project again and I have solved the issue by re-watching Eddie's series again (I still couldn't fight out my initial issue but it works fine now), after I solve some other bugs found I will notify you if you are still interested in this

**Comment by MichaelChar** [comment]
Looking forward!

**Comment by Radu-Sebastian** [comment]
https://github.com/Radu-Sebastian/Python-Chess-AI-With-Digital-Board-Recognition-And-MCTS
